<template>
  <div class="settings" :class="{ 'settings--open': open }">
    <div class="settings__bar">
      <button class="settings__toggle" @click="$emit('toggle')">
        {{ open ? 'Close' : 'Open' }} Settings
      </button>
    </div>

    <div class="settings__content" v-if="open">
      <h3>Layout</h3>
      <label>
        <input type="checkbox" v-model="local.header.enabled" /> Header
      </label>

      <div class="row">
        <label>Footer</label>
        <select v-model="local.footer.type">
          <option :value="null">None</option>
          <option value="simple">Simple</option>
          <option value="page">Page</option>
        </select>
      </div>

      <h3>Sections</h3>
      <div class="row">
        <button @click="addSection('cards')">Add Cards</button>
        <button @click="addSection('logos')">Add Logos</button>
        <button @click="addSection('base')">Add Base</button>
      </div>

      <ul class="list">
        <li v-for="(s, i) in local.sections" :key="s.id">
          <span>{{ s.type }}</span>
          <button @click="removeSection(i)">Remove</button>
        </li>
      </ul>

      <div class="row end">
        <button class="primary" @click="apply">Apply</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, watch, toRaw } from 'vue'

const props = defineProps<{ open: boolean }>()
const emit = defineEmits<{ (e: 'toggle'): void; (e: 'apply', value: any): void }>()

const local = reactive({
  header: { enabled: true },
  footer: { type: 'simple' as 'simple' | 'page' | null, props: {} as any },
  sections: [] as Array<{ id: string; type: 'base' | 'cards' | 'logos'; props: any }>
})

function addSection(type: 'base' | 'cards' | 'logos') {
  const id = Math.random().toString(36).slice(2)
  if (type === 'cards') {
    local.sections.push({
      id, type,
      props: {
        title: 'New Cards',
        description: 'Autogenerated cards section',
        columns: 3,
        cards: [
          { id: id + '-1', icon: 'compass', title: 'Card A', subtitle: 'Sub', content: 'Lorem ipsum.' },
          { id: id + '-2', icon: 'rocket', title: 'Card B', subtitle: 'Sub', content: 'Dolor sit.' },
          { id: id + '-3', icon: 'star-m', title: 'Card C', subtitle: 'Sub', content: 'Amet.' }
        ]
      }
    })
    return
  }
  if (type === 'logos') {
    local.sections.push({
      id, type,
      props: {
        variant: 'scroller',
        logos: [
          { id: id + '-1', icon: 'compass' },
          { id: id + '-2', icon: 'rocket' },
          { id: id + '-3', icon: 'star-m' }
        ]
      }
    })
    return
  }
  local.sections.push({ id, type, props: { label: 'Base Section' } })
}

function removeSection(index: number) {
  local.sections.splice(index, 1)
}

function apply() {
  const cfg = {
    header: local.header,
    footer: local.footer,
    sections: local.sections.map(s => ({ id: s.id, type: s.type, props: s.props }))
  }
  emit('apply', JSON.parse(JSON.stringify(cfg)))
}
</script>

<style scoped>
.settings {
  --settings-panel-height: 56px;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
}
.settings__bar {
  height: var(--settings-panel-height);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 1rem;
  background: color-mix(in srgb, var(--color-foreground), transparent 92%);
  backdrop-filter: blur(6px);
  border-bottom: 1px solid var(--color-border);
}
.settings__toggle {
  background: transparent;
  border: 1px solid var(--color-border);
  border-radius: 6px;
  padding: 0.5rem 0.75rem;
}
.settings__content {
  background: color-mix(in srgb, var(--color-background), transparent 5%);
  border-bottom: 1px solid var(--color-border);
  padding: 1rem;
}
.row { display: flex; gap: 0.75rem; align-items: center; margin: 0.5rem 0; }
.row.end { justify-content: flex-end; }
.list { list-style: none; padding: 0; margin: 0.5rem 0; }
.list li { display: flex; gap: 0.5rem; align-items: center; }
.primary { background: var(--color-primary); color: var(--color-primary-text); border: none; padding: 0.5rem 0.75rem; border-radius: 6px; }
</style>

