<template>
  <div class="settings" :class="{ 'settings--open': open }">
    <div class="settings__bar">
      <button class="settings__toggle" @click="$emit('toggle')">
        {{ open ? 'Close' : 'Open' }} Settings
      </button>
    </div>

    <div class="settings__content" v-if="open">
      <h3>Layout</h3>
      <label>
        <input type="checkbox" v-model="local.header.enabled" /> Header
      </label>

      <div class="row">
        <label>Footer</label>
        <select v-model="local.footer.type">
          <option :value="null">None</option>
          <option value="simple">Simple</option>
          <option value="page">Page</option>
        </select>
      </div>

      <h3>Sections</h3>
      <div class="row">
        <button @click="addSection('cards')">Add Cards</button>
        <button @click="addSection('logos')">Add Logos</button>
        <button @click="addSection('base')">Add Base</button>
      </div>

      <div class="section-editor" v-for="(s, i) in local.sections" :key="s.id">
        <div class="section-editor__header">
          <strong>{{ i + 1 }}. {{ s.type }}</strong>
          <button @click="removeSection(i)">Remove</button>
        </div>

        <div v-if="s.type === 'cards'" class="grid">
          <label>
            Title
            <input type="text" v-model="s.props.title" />
          </label>
          <label>
            Description
            <input type="text" v-model="s.props.description" />
          </label>
          <label>
            Columns
            <input type="number" min="1" max="6" v-model.number="s.props.columns" />
          </label>
          <label>
            Card count
            <input type="number" min="1" max="12" v-model.number="s.props.cardCount" @change="syncCardCount(s)" />
          </label>
          <div class="row">
            <button @click="regenerateCards(s)">Regenerate cards</button>
          </div>
        </div>

        <div v-else-if="s.type === 'base'" class="grid">
          <label>
            Label
            <input type="text" v-model="s.props.label" />
          </label>
        </div>

        <div v-else-if="s.type === 'logos'" class="grid">
          <label>
            Variant
            <select v-model="s.props.variant">
              <option value="scroller">scroller</option>
              <option value="grid">grid</option>
            </select>
          </label>
          <label>
            Logo count
            <input type="number" min="3" max="20" v-model.number="s.props.logoCount" @change="syncLogoCount(s)" />
          </label>
          <div class="row">
            <button @click="regenerateLogos(s)">Regenerate logos</button>
          </div>
        </div>
      </div>

      <div class="row end">
        <button class="primary" @click="apply">Apply</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive } from 'vue'
import { faker } from '@faker-js/faker'

const props = defineProps<{ open: boolean }>()
const emit = defineEmits<{ (e: 'toggle'): void; (e: 'apply', value: any): void }>()

const local = reactive({
  header: { enabled: true },
  footer: { type: 'simple' as 'simple' | 'page' | null, props: {} as any },
  sections: [] as Array<{ id: string; type: 'base' | 'cards' | 'logos'; props: any }>
})

const ICONS = ['compass', 'rocket', 'star-m', 'graph-up', 'info-l']
function randIcon() { return ICONS[Math.floor(Math.random() * ICONS.length)] }
function genCard(id: string) {
  return { id, icon: randIcon(), title: faker.commerce.productName(), subtitle: faker.commerce.department(), content: faker.commerce.productDescription() }
}
function genCards(n: number, prefix = 'c') { return Array.from({ length: n }, (_, idx) => genCard(`${prefix}-${idx + 1}`)) }
function genLogos(n: number, prefix = 'l') { return Array.from({ length: n }, (_, idx) => ({ id: `${prefix}-${idx + 1}`, icon: randIcon() })) }

function addSection(type: 'base' | 'cards' | 'logos') {
  const id = Math.random().toString(36).slice(2)
  if (type === 'cards') {
    local.sections.push({
      id, type,
      props: {
        title: 'New Cards',
        description: 'Autogenerated cards section',
        columns: 3,
        cardCount: 3,
        cards: genCards(3, id)
      }
    })
    return
  }
  if (type === 'logos') {
    local.sections.push({
      id, type,
      props: {
        variant: 'scroller',
        logoCount: 5,
        logos: genLogos(5, id)
      }
    })
    return
  }
  local.sections.push({ id, type, props: { label: 'Base Section' } })
}

function removeSection(index: number) {
  local.sections.splice(index, 1)
}

function apply() {
  const cfg = {
    header: local.header,
    footer: local.footer,
    sections: local.sections.map(s => {
      const props = { ...s.props }
      if (s.type === 'cards') delete (props as any).cardCount
      if (s.type === 'logos') delete (props as any).logoCount
      return { id: s.id, type: s.type, props }
    })
  }
  emit('apply', JSON.parse(JSON.stringify(cfg)))
}

function syncCardCount(s: any) {
  const n = Math.max(1, Math.min(12, Number(s.props.cardCount || 1)))
  s.props.cards = genCards(n, s.id)
}
function regenerateCards(s: any) {
  const n = Number(s.props.cardCount || (s.props.cards?.length ?? 3))
  s.props.cards = genCards(n, s.id)
}
function syncLogoCount(s: any) {
  const n = Math.max(3, Math.min(20, Number(s.props.logoCount || 3)))
  s.props.logos = genLogos(n, s.id)
}
function regenerateLogos(s: any) {
  const n = Number(s.props.logoCount || (s.props.logos?.length ?? 5))
  s.props.logos = genLogos(n, s.id)
}
</script>

<style lang="scss">
.settings {
  --settings-panel-height: 56px;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;

  // make sure to use var(--space-X)sizes for all sizes. NO HARD PIXEL SIZES.

  &__bar {
    height: var(--settings-panel-height);
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 1rem;
    background: color-mix(in srgb, var(--color-foreground), transparent 92%);
    backdrop-filter: blur(6px);
    border-bottom: 1px solid var(--color-border);
  }

  &__toggle {
    background: transparent;
    border: 1px solid var(--color-border);
    border-radius: 6px;
    padding: 0.5rem 0.75rem;
  }

  &__content {
    background: color-mix(in srgb, var(--color-background), transparent 5%);
    border-bottom: 1px solid var(--color-border);
    padding: 1rem;
  }


// Clean below up, needs to be bem as well. We don't ever style like this below.
.row {
  display: flex;
  gap: 0.75rem;
  align-items: center;
  margin: 0.5rem 0;
}

.row.end {
  justify-content: flex-end;
}

.list {
  list-style: none;
  padding: 0;
  margin: 0.5rem 0;
}

.list li {
  display: flex;
  gap: 0.5rem;
  align-items: center;
}

.primary {
  background: var(--color-primary);
  color: var(--color-primary-text);
  border: none;
  padding: 0.5rem 0.75rem;
  border-radius: 6px;
}
}

</style>

<style scoped>
.section-editor { border: 1px solid var(--color-border); border-radius: 8px; padding: 0.75rem; margin: 0.5rem 0; }
.section-editor__header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
.grid { display: grid; grid-template-columns: repeat(2, minmax(160px, 1fr)); gap: 0.5rem 0.75rem; }
.grid label { display: flex; flex-direction: column; font-size: 0.9rem; }
.grid input, .grid select { padding: 0.25rem 0.5rem; border: 1px solid var(--color-border); border-radius: 6px; background: transparent; color: inherit; }
</style>
